const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Rolex',
        item_name: 'Rolex deepsea',
        original_price: 12000,
        current_price: 9000,
        discount_percentage: 25,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.png',
        company: 'PCB',
        item_name: '1992 wining jersey',
        original_price: 350,
        current_price: 300,
        discount_percentage: 14.5,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3.png',
        company: ' DAR UL MISK',
        item_name: 'Ghilaf E Kaaba "Attar"',
        original_price: 200,
        current_price: 140,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4.jpeg',
        company: 'Samsung',
        item_name: 'Samsung J6',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5.jpeg',
        company: 'Grey Nicolls',
        item_name: 'Grey nicolls Bat',
        original_price: 13999,
        current_price: 48900,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'kokabora',
        item_name: 'kokabora hardball',
        original_price: 1495,
        current_price: 1425,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpeg',
        company: 'SA',
        item_name: 'Ehram',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpeg',
        company: 'Garmin',
        item_name: 'Sports Watch',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];

